{% set name = "opa" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-policy-agent/opa/archive/v{{ version }}.tar.gz
  sha256: a98386cf64eaff62003d844244e8e1587edf36b2306c5395d221b6b5b62cf824

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - opa --help

about:
  home: https://github.com/open-policy-agent/opa
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Open Policy Agent (OPA) is an open source, general-purpose policy engine.
  dev_url: https://github.com/open-policy-agent/opa

extra:
  recipe-maintainers:
    - danielnachun
