schema_version: 1

context:
  version: "1.11.1"

package:
  name: opa
  version: ${{ version }}

source:
  url: https://github.com/open-policy-agent/opa/archive/v${{ version }}.tar.gz
  sha256: 4b4208bdf1aeb91def3ba3a42236d21b98dd35b2a92769baadb76c3950399023

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - opa --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Open Policy Agent (OPA) is an open source, general-purpose policy engine.
  homepage: https://github.com/open-policy-agent/opa
  repository: https://github.com/open-policy-agent/opa

extra:
  recipe-maintainers:
    - danielnachun
