schema_version: 1

context:
  version: "1.18.1"

package:
  name: opa
  version: ${{ version }}

source:
  url: https://github.com/open-policy-agent/opa/archive/v${{ version }}.tar.gz
  sha256: b778447b1b6c5c3c8ed67a468477697970db0135b5b20ffe75d510f65a4f4b52

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - opa --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Open Policy Agent (OPA) is an open source, general-purpose policy engine.
  homepage: https://github.com/open-policy-agent/opa
  repository: https://github.com/open-policy-agent/opa

extra:
  recipe-maintainers:
    - danielnachun
