schema_version: 1

context:
  version: "1.19.1"

package:
  name: opa
  version: ${{ version }}

source:
  url: https://github.com/open-policy-agent/opa/archive/v${{ version }}.tar.gz
  sha256: 7d862fb8d91785d5af4cd29ef55813feb1db3977de4242371d3aec3fed49309a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - opa --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Open Policy Agent (OPA) is an open source, general-purpose policy engine.
  homepage: https://github.com/open-policy-agent/opa
  repository: https://github.com/open-policy-agent/opa

extra:
  recipe-maintainers:
    - danielnachun
