schema_version: 1

context:
  version: "1.12.1"

package:
  name: opa
  version: ${{ version }}

source:
  url: https://github.com/open-policy-agent/opa/archive/v${{ version }}.tar.gz
  sha256: 52dbb092c56102fff61bb920d441e8b4f578f504ed087008015a9ae577d03caa

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - opa --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Open Policy Agent (OPA) is an open source, general-purpose policy engine.
  homepage: https://github.com/open-policy-agent/opa
  repository: https://github.com/open-policy-agent/opa

extra:
  recipe-maintainers:
    - danielnachun
