schema_version: 1

context:
  version: "1.13.2"

package:
  name: opa
  version: ${{ version }}

source:
  url: https://github.com/open-policy-agent/opa/archive/v${{ version }}.tar.gz
  sha256: 9a1d696c157d15cd95d6e360ec2ef543aa4c741e825dbaf061259b00f0c15f82

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - opa --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Open Policy Agent (OPA) is an open source, general-purpose policy engine.
  homepage: https://github.com/open-policy-agent/opa
  repository: https://github.com/open-policy-agent/opa

extra:
  recipe-maintainers:
    - danielnachun
